### PR TITLE
Convert the rest of cursor to nearest pow-of-2

### PR DESCRIPTION
**Pull request by xponen**
Resize masse,erom,lathan, and ca_static cursor set to nearest power-of-2 size
Added automation script (for Windows) for future reference!

related to https://github.com/ZeroK-RTS/Zero-K/issues/704
so far there's no image greater than 64x64 and majority is 32x32

### CODE REVIEW

**Comment by sprunk** [comment]
These new images do not obey hotspots properly.

**Comment by xponen** [comment]
@sprunk what is the correct hotspot?
I will try to make the conversion properly.

**Comment by sprunk** [comment]
Also, some of them had a lot of empty border space and could safely be downsized to 32 (instead of upsized to 64). Remember that cards where >32 is a problem exist.

**Comment by xponen** [comment]
okay ty @sprunk  
I will find out how to script empty space trimmer

**Comment by xponen** [comment]
tested each file for hotspot, transparency, aspect ratio after padding, now all okay.
although no resize to 32x32 because 32x32 or 64x64 seems to work for me.

**Pull request merged**
