### PR TITLE
Reduced Mistral flightTime (5->3) and remove weaponTimer from non-Starburst defs.

### PR DESCRIPTION
**Pull request by Aquanim**
Accounts for increased missile speed compared to Enforcer, and probably makes it a little worse against Swift.
Also redesignated Missile Frigate -> Missile Boat.

### CODE REVIEW

**Comment by sprunk** [comment]
As far as I can tell weaponTimer does nothing on non-Starburst weapons. Is there any observable change?

**Comment by Aquanim** [comment]
I *think* that if the weaponTimer expires the missile no longer does damage, but I can test that further by making it something extreme.

The flightTime is the important change though.

**Comment by Anarchid** [comment]
The correct thing to do to both Slasher and Mistral's weaponTimer is to abolish them.

**Comment by sprunk** [comment]
I believe 0-damage shots are due to impactOnly == false.

**Pull request merged**
