### PR TITLE
Fix #424 and #637 - show vertical lines for UW units

### LINKED ISSUE #424: Better Defense circles needed for amph warfare
Currently when playing with anything amphibian defense ranges drawn can not be relied upon for precise army movement because circles are only drawn above water and not on the ground surface below water.

To clarify:
Build two torpedo launchers in a deep ocean, build them far enough apart to leave a small gap between their range circles. Share them to an enemy player.
Now try to use the defense range drawn for them to move one or multiple Ducks through the gap without taking damage.

Another example is using Bouys and Scallops to kill torpedo launchers from afar without being inside the defense range of other nearby torpedo launcher (or when using Bouys even Defenders).

### LINKED ISSUE #637: Team color nearly invisible in sea
Team game battles are really hard to understand with default settings

http://i.imgur.com/gTCIEs5.jpg

### PR DESCRIPTION
**Pull request by sprunk**
Fixes #424, the lines point to the surface.

Also fixes #637, the lines are team colored. Not the best visuals but we get it for free when fixing 424.

### CODE REVIEW

**Comment by GoogleFrog** [comment]
Are these visible while in LOS?

**Comment by sprunk** [comment]
There are two settings for enemy units, (only in radar) or (anywhere, ie either radar or los). The PR uses the second.

**Comment by Licho1** [comment]
Meh would be better if radar didnt report any height (for air too, it gives too much info imo)

**Comment by Skasi** [comment]
Hmm looks like this didn't properly close #424 and #637 like it should have.

**Comment by sprunk** [comment]
This is a hanging PR. It won't close the tickets until (unless) it is merged.

**Comment by Skasi** [comment]
Oh, I didn't see the "Open" thingie. My bad!

**Pull request merged**
