### PR TITLE
Add global build command widget

### PR DESCRIPTION
**Pull request by mtroyka**
Please review/test

-Added global build command widget (and terraform support)
-Added callin code to gui_lasso_terraform so that other widgets can see the commands it gives and capture them

(note: it can't handle the build part of raise-and-build, but raise-and-build still works as long as it's given as a direct order)

### CODE REVIEW

**Comment by xponen** [comment]
I'll test gui_lasso_terraform changes

**Comment by mtroyka** [comment]
I'm currently trying to see if I can't properly capture raise-and-build, but the way it's written in gui_lasso_terraform is difficult to deal with, and needs to have more compatibility code added. :|

**Comment by GoogleFrog** [comment]
I don't see much purpose in including this but historically it is the sort of thing we do because we are nice.

**Comment by mtroyka** [comment]
Alright, this should be ready to merge. There's nothing left to implement and I've tested it half to death.

**Comment by GoogleFrog** [comment]
I'm not sure when or if I should merge this.

**Pull request closed without merging**
