### PR TITLE
Cleanup Unit Marker

### PR DESCRIPTION
**Pull request by sprunk**

### CODE REVIEW

**Comment by xponen** [comment]
IMO delayed refresh & com upgrade message don't need to be deleted.

com upgrade message worked fine 
and delayed refresh avoid unnecessary Marker when scythe decloak rapidly

**Comment by sprunk** [comment]
Not the proper place to add 1
2 is implemented, read the code

**Comment by xponen** [comment]
2 is not implemented, see 
https://github.com/sprunk/Zero-K/blob/patch-115/LuaUI/Widgets/unit_marker.lua#L44

this added marker each time Scythe appear. In previous code it add marker if Scythe re-discovered after 5 second.

Its rude to not add you as author when you delete the original code.

**Comment by Anarchid** [comment]
`git blame` exists, so author-attribution is probably superfluous.

**Comment by sprunk** [comment]
Read the previous code to see what 2 really did (hint: it did the same thing the new one does.
Git can handle last update date and authorship.

**Comment by xponen** [comment]
okay nvm, I'll add timer later, or you can add it if you want to help.

**Comment by sprunk** [comment]
timer is not needed

**Comment by xponen** [comment]
worse thing about this PR is:
widget barely have code from original author, but never want to add self to author name.

**Pull request merged**
