### PR TITLE
Build bar widget

### PR DESCRIPTION
**Pull request by TRONAS**
screen00019

### CODE REVIEW

**Comment by TRONAS** [comment]
works better than the others imho

**Comment by GoogleFrog** [comment]
Wow this looks like super old pre chili.

**Comment by Licho1** [comment]
13 year old jK's original widget.. archeology!

**Comment by sprunk** [comment]
>works better than the others imho

Explain "better". Any improvements would ideally be extracted and ported to
https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaUI/Widgets/gui_chili_facbar.lua (and facpanel, if applicable) since this one is not chili (harder to maintain, or port to develop in the future) and it would be the third version of what is basically the same widget.

**Comment by TRONAS** [comment]
its transparent, the icons are bigger and opens build options when hovered

**Comment by sprunk** [comment]
Good, so I think the thing to do would be to add opacity/size sliders to the existing Chili versions and a checkbox to open when hovered.

**Comment by GoogleFrog** [comment]
I would not be surprised if this performs a lot better than any previous chili version of facbar. If this works then it seems worthwhile adding it.

**Comment by Licho1** [comment]
Remember jK made both this and chili..

**Pull request closed without merging**
