### PR TITLE
replay_controls.lua: add easy to use fast-forward function to help debug stuff

### PR DESCRIPTION
**Pull request by xponen**
Really simple but neat feature, just click at any time to fast forward to, the game will be paused when you got back to it. 
replay bar update

### CODE REVIEW

**Comment by GoogleFrog** [comment]
What is the weird grey arrow?

Add a tooltip to the bar which tells you the time that will be jumped to. Make it clear that you cannot jump backwards.

Make an option to hide the bar because it is possibly a spoiler to know how long a game is.

**Comment by sprunk** [comment]
The site already spoils duration.
Presumably, arrow is cursor.
Tooltip for the time that will be jumped to seems to exist (see 3rd and 4th picture).

**Comment by xponen** [comment]
@GoogleFrog IMO is good enough, 

IMO it isn't much spoiler because
game minute won't show up if we didn't hover over the bar, and there's time in pre-game to drag the window offscreen.

if that don't work, then we can fix.

**Comment by GoogleFrog** [comment]
You should never have to drag something offscreen. All this needs is a toggle in the menu to hide/unhide the bar.

**Comment by xponen** [comment]
Ok
have made bar hidden (disabled) by default. Also work better than before.

To activate progress bar, double click it. Visual feedback is added to explain its clickable.

**Pull request merged**
