### PR TITLE
Chickens can no longer be reclaimed

### LINKED ISSUE #3809: Consider making chicken units unreclaimable
Mostly for fluff reasons, though many of them have 0 metal value anyway

### PR DESCRIPTION
**Pull request by Arch-Shaman**
Fixes #3809
* Sets all chicken unitdefs to `reclaimable = false`

### CODE REVIEW

**Comment by Feugent** [comment]
Why was this necessary? This breaks chickenfactory for Zero-Wars.

**Comment by Arch-Shaman** [comment]
An issue was open at the time and it seemed like an easy fix.

**Comment by sprunk** [comment]
How does reclaim affect a factory?

**Comment by Arch-Shaman** [comment]
I'm presuming they mean it has some broken gameplay effect?

**Comment by Feugent** [comment]
It does not affect the fac itself but the ability to change the currently used chicken units in the spawning platform.
Talked with PetTurtle and he said he will fix it in Zero-Wars itself.
Idk why the change to non reclaimable was necessary though.

**Comment by Arch-Shaman** [comment]
> Idk why the change to non reclaimable was necessary though.

> Mostly for fluff reasons, though many of them have 0 metal value anyway

I don't see how reclaiming a 0m unit is anything other than an area reclaim live unit work sink. Plus it looks silly.

**Comment by PetTurtle** [comment]
I believe only the chickens player can reclaim the chickens, but it's currently impossible to be the chickens player.
Also zero-wars fixed chickens having 0 metal value.
```
for _, ud in pairs(UnitDefs) do
    if (ud.unitname:sub(1, 7) == "chicken") then
        ud.buildcostmetal = ud.buildtime
        ud.buildcostenergy = ud.buildtime
    end
end
```
I'm not sure why this is not the case with default chickens, but it does help show the value of the chickens your fighting.

**Pull request merged**
