### PR TITLE
Lua unitscripts for Leveler and Ravager (mostly copied from banisher) + small bugfix

### PR DESCRIPTION
**Pull request by lhog**
For review and not necessarily for merge.

### CODE REVIEW

**Comment by GoogleFrog** [comment]
The wheels clip through their wheel housings which is a problem. Also when the units fire the wheels do not show any suspension.

**Comment by lhog** [comment]
Regarding 1st point. Is it for all units or some specific ones? Can you do a screenshot?
2) If you/anyone knows how to fix both, you/that person better do that. I'm not very good with unitscripts.

**Comment by GoogleFrog** [comment]
The second issue is probably caused by the rock script not changing the location of the wheel contact pieces.

**Comment by lhog** [comment]
I've done some experimenting few days ago and found out that, Rocking base piece of model causes change of wheels' vertical position at least. And this is what suspension script is looking for.

Also the issue is probably caused by difference in explicit Rock scripts parameters such as force and speed and "magic constants" that are used to calculate ztilt and xtilt. I removed x/z tilt handling few days ago and got sane results. When I have time I'll try to put them back but make them aligned so one effect does not contradict with other.

**Comment by GoogleFrog** [comment]
Look at the piece hierarchy. It may need changing if the wrong piece is being rocked or you require a stable piece.

**Comment by GoogleFrog** [comment]
I don't think this is going anywhere.

**Pull request closed without merging**
