### PR TITLE
trying to make GetSpiralGenerator utility for the issue #5197

### PR DESCRIPTION
**Pull request by IcarusRTS**
I need some assistance with this one as right now, start_unit_setup that has this utility integrated causes Zero-K to freeze then crash.

### CODE REVIEW

**Comment by sprunk** [comment]
Perhaps leave `start_unit_setup.lua` alone for now and just make sure the utility passes the provided tests (via a widget).

Freeze and a subsequent crash most likely means you have an infinite loop.

**Comment by IcarusRTS** [comment]
I did actually make two test widgets prior to the pull request and the debug log gave zero errors ingame (unless there is something else I need to do for testing, if so, tell me)

**Comment by sprunk** [comment]
> the debug log gave zero errors ingame

Check `infolog.txt`, Ctrl+F "test1_sg.lua" or whatever was the name of the file.

**Comment by IcarusRTS** [comment]
> > the debug log gave zero errors ingame
> 
> Check `infolog.txt`, Ctrl+F "test1_sg.lua" or whatever was the name of the file.

Good news, both test widgets load in properly now.

Bad news is that there are new issues to tackle.

image

**Pull request closed without merging**
