### PR TITLE
Misc unit_auto_patrol_nanos_v2 improvements.

### LINKED ISSUE #4226: Smart Nanos stuck on reclaim for a while when excessing metal.
image

In this battle: http://zero-k.info/Battles/Detail/1006569

### PR DESCRIPTION
**Pull request by rtwfroody**
* Do less work when viewing a replay.
* Add some more debug info (only when the widget is edited to set
  debug=true).
* Fix my understanding of reclaim commands. There is no "reclaim
  energy," but only "reclaim all." I think this fixes #4226.
* Tolerate spGetUnitResources() returning nil, which happened to me
  once.

I've been using this for 2 weeks with no issues.

### CODE REVIEW

**Review by sprunk — APPROVED** [review]
Looks good

**Comment by rtwfroody** [comment]
Bump.

**Comment by GoogleFrog** [comment]
I'll mark it for the next PR update. I think there will be a few small handicap tweaks for now so don't want to add potential bugs for now.

**Comment by rtwfroody** [comment]
Thank you.

**Pull request merged**
