### PR TITLE
COFC: Improve smoothmesh following

### PR DESCRIPTION
**Pull request by CrazyEddieTK**
Fixed math in smoothmesh following to reduce jumping when starting to scroll. It still jumps if the difference between the smoothmesh and heighmap countours are large and sharp, but this is a big improvement.

### CODE REVIEW

**Comment by CrazyEddieTK** [comment]
... just to clarify - the math is the same (just slightly rearranged). The only real difference is removing the condition, which was only applying the correction when facing east.

**Comment by GoogleFrog** [comment]
How is this @dvr333?

**Comment by sprunk** [comment]
At a glance looks legit

**Comment by Anarchid** [comment]
That can be done at merge time 
image

**Comment by CrazyEddieTK** [comment]
Will resubmit in a new PR using a clean branch.

**Pull request closed without merging**
