### PR TITLE
Factoryveh remodel WIP

### PR DESCRIPTION
**Pull request by Anarchid**
Supercedes previous.

Todo:

- [x] decal
- [x] tune closing animation
- [x] more teamcolor
- [x] rotate buildee to face front
- [x] footprint
- [x] colvol
- [x] radius
- [x] dae is crap at making functional nanoframes.
- [x] there is a gap between the bottom of the factory and the ground.
- [x] death animation.
- [x] disable animation while stunned or inbuild.

### CODE REVIEW

**Comment by GoogleFrog** [comment]
Very little teamcolour is visible from the top. Most of the colour is yellow lights so it looks more like a yellow unit than a green unit.

Impaler is square so the shipping container should be a bit longer to make the unit-pad square. Then units can leave the factory to the South without sticking over the edge of the pad.

Your division of tasks is unusual. I will make the ground decal. You need to rotate the model by 90 degrees. 

screen00530

**Comment by Anarchid** [comment]
I did the turning withotu lenghtening the capsule. Impaler seems to fit reasonably well. 
image

**Comment by sprunk** [comment]
How hard would it be to rescale? Looks odd because it sticks out.

**Comment by Anarchid** [comment]
team: colored 
image

**Comment by Anarchid** [comment]
Also i checked the closing anim after rotating the model back. It seems okay.

**Comment by Anarchid** [comment]
> How hard would it be to rescale? Looks odd because it sticks out.

Scaling will require animation to be redone. Aside from that, easy enough.

**Comment by GoogleFrog** [comment]
I think its worth trying with a square shipping capsule. It looks weird at the moment because most rovers are longer than they are wide. This makes them look misaligned when they are at right angles to a rectangle of similar dimensions. The back end of the capsule just needs extending towards the main body of the factory.

I think I am able to do the rest of the required things (decal, footprint etc..).

**Comment by Anarchid** [comment]
Capsule lengtified to accomodate impalator superiorly
image

**Comment by GoogleFrog** [comment]
screen00531

**Comment by GoogleFrog** [comment]
@Anarchid it is your job to fix the dae nanoframe terribleness.

**Comment by Anarchid** [comment]
Extents work. The coordinate order is spring ingame (y is altitude).

 i guess the issue without hardwired extents is with spring somehow erroneously detecting model's lowest point to be somewhere deep below. 

Possibly because because of conflict between Z-up in blender collada and Y-up in Spring, and extent calculation being done before the space is converted.

**Pull request merged**
