### PR TITLE
⚙️ Change some defs keys to match UnitDefs

### PR DESCRIPTION
**Pull request by sprunk**
In wupgets, you use for example `UnitDefs[x].metalCost`. But in unit def files it's `buildCostMetal`. This is needlessly confusing. New engine added support for matching keys recently, so apply some of these:

 * buildCostMetal → metalCost
 * buildCostEnergy → energyCost
 * energyUse → energyUpkeep
 * metalUse → metalUpkeep (vanilla ZK doesn't use this)

Mods who use the old spelling are supported for now.

### CODE REVIEW

**Comment by GoogleFrog** [comment]
I am a bit conflicted about the unitdefs. On one hand, they're supposed to be alphabetical. On the other hand, I am used to looking near the top for metal cost. There is also the fact that units with energy cost specified would now have their costs spread around the file. There is precedent for related parameters to be grouped though (collision volume and selection volume).

**Comment by GoogleFrog** [comment]
So that there is a decision, I'll go with making metal cost alphabetical, and putting energy cost and worker time below metal cost in the cases where they exist.

**Comment by sprunk** [comment]
> and worker time

I'll assume this is buildTime and not workerTime which is buildpower.

**Comment by GoogleFrog** [comment]
Yes.

**Pull request merged**
