### PR TITLE
Widget to remove mearth locations

### PR DESCRIPTION
**Pull request by ArchShaman**
This widget can remove crap that's broken from maps.

### CODE REVIEW

**Comment by sprunk** [comment]
Tested? Layer looks suspicious.

**Comment by ArchShaman** [comment]
>Tested? Layer looks suspicious.

Tested. Code executes as intended. I tried to make it load last, just to be on the safe side. Tested with layer = 5, works as intended too. So I'll change to 5.

>License is pretty much Horse again. If you wish to include files under the "Resignateer License", you should also provide text of this license.

For all intents and purposes, all my code, future, past, and current, falls under the policy of "do whatever with it". I'll change it to reflect this, if necessary.

**Comment by ArchShaman** [comment]
Can I commit future code with "Shaman's policy" now that it has some text reference?

**Comment by Anarchid** [comment]
"Do whatever" sounds very much like "public domain", so why not just use that?

**Comment by ArchShaman** [comment]
Gonna add reasons to this.

>"Do whatever" sounds very much like "public domain", so why not just use that?

Cuz I don't/didn't know what "Public domain" is. I'll add it in with my reasoning thing I want to add.

**Comment by ArchShaman** [comment]
[f=-000001] Disabled '*Mearth Location Tags*1.0' (Reason: Causes black ground on some cards, possible copyright issues.)
[f=-000001] Loaded widget:  Disable Bad Widgets  <widgetdisabler.lua>

**Comment by ArchShaman** [comment]
Only problem that this may have is that there's no `widgetHandler:FindWidget` function, so on other maps it will complain about the bad widgets not existing. I may have to include a cawidgets.lua change to fix that.

**Comment by sprunk** [comment]
e6f3c516faec7c088a17c084b7df852a4ffb29ce

**Pull request merged**
