### PR TITLE
Formatted README

### PR DESCRIPTION
**Pull request by ElectronicsArchiver**
[Badge Suggestions]: https://img.shields.io/badge/Ｒｅｐｏｓｉｔｏｒｙ_Ｓｕｇｇｅｓｔｉｏｎｓ-609926?style=for-the-badge&logoColor=white&logo=GitHub
[Badge Changes]: https://img.shields.io/badge/Ｃｈａｎｇｅｓ-D81939?style=for-the-badge&logoColor=white&logo=GitLFS
[Badge Robot]: https://img.shields.io/badge/Ｉ＇ｍ_Ｈｕｍａｎ-c84f8c?style=for-the-badge&logoColor=white&logo=RuboCop
[Badge Ask]: https://img.shields.io/badge/Ｐｌｅａｓｅ_Ａｓｋ_Ｍｅ-73398D?style=for-the-badge&logoColor=white&logo=AskUbuntu

[License Badges]: https://github.com/MarkedDown/Licenses
[Widgets]: https://github.com/MarkedDown/Disable/blob/main/Features/Widgets.md
[Tabs]: https://github.com/MarkedDown/Disable/blob/main/Features/Tabs.md
[Wiki]: https://github.com/MarkedDown/Wiki

<br>
<br>

<div align = center>

[<kbd> <br> Please Check The **Preview** <br> </kbd>][Preview]

</div>
  
<br>
<br>

## ![Badge Suggestions]

  <br>

- **Add Tags**

  - `game`
  - `real-time-strategy`
  - `spring-engine`

  <br>

- **Update Description**

  `RTS Game built on the Spring Engine.`

  <br>

- ***[Disable unused Widgets][Widgets]***:

  - `Packages`

  - `Releases`

  <br>

- ***[Disable unused Tabs][Tabs]***:

  - `Actions`
  
  <br>
  
- ***[Why not to use GitHub Wiki][Wiki]***

  <br>

<br>
<br>

## ![Badge Changes]

- General formatting / spacing

- Linked spring engine

- Added license badge

<br>
<br>

## ![Badge Ask]

- ***If you have any questions.***

- ***In case you do not agree with some of the changes made in this PR***, <br>
  *please first let me know about them, before disregarding it entirely so*<br>
  *we can possibly find a middle ground and have it not go to waste.*

<br>
<br>

## ![Badge Robot]

<kbd> <br>            No, I'm not a robot.            <br> </kbd>

<kbd> <br>    Yes, you are not the first.    <br> </kbd>

<kbd> <br>     I just made a PR template.     <br> </kbd>

<br>
<br>

[Preview]: https://github.com/ElectronicsArchiver/Zero-K

### CODE REVIEW

**Comment by sprunk** [comment]
Nice, why the `<br/>` though? Leaves an ugly empty space.
image

**Comment by ElectronicsArchiver** [comment]
> Nice, why the <br/> though? Leaves an ugly empty space.

The same reason why books and articles do it,
human perception only reaches about 60 chars.

I usually go with 60 - 80 and try to form lines
of blocks of equal lengths to make it look less
distraught..

In your case a centered layout 
might do well, should I try it?

**Comment by ElectronicsArchiver** [comment]
Here you go~

Btw, you might like the alternate license badge style better:

https://github.com/Fresh791/Fading-Revelations

*Another repo I formatted~*

**Comment by sprunk** [comment]
> The same reason why books and articles do it,

I thought books and articles do it because that's just how large a sheet of paper and a mobile display tends to be.

Anyway, thanks, I think I can get rid of the empty space myself and the non-plaintext links are probably an improvement.

**Pull request merged**
