### PR TITLE
Some adjustments to terraform look & internals:

### PR DESCRIPTION
**Pull request by lhog**
1) terraunit is shown using an icon, instead of current debris model
2) Removed terraTag from the gadget. No one used it, including myself (original author). commandTag should be good enough alone
3) Added terraForm type just in case someone finds a good way to display a unit icon, specific to terraform type (e.g. ramp, level, etc). I'd tried WG.icons.SetUnitIcon and couldn't get a good visual result.

### CODE REVIEW

**Comment by quantumv** [comment]
Hurrah for icons! The debris were really ugly (I'm the one responsible for them!).

**Comment by lhog** [comment]
Unfortunately, I couldn't make an icon switch depending on terraform type. One easy way would be to make 6 terraunit types with 6 different icons respectively. Sadly it'd break checks like ```unitDefID==terraDefID``` in various widgets & gadgets

**Comment by GoogleFrog** [comment]
I dislike the unsynced section being in the gadget. Ideally you would set their icon distance so low that they will always be drawn as an icon. I don't remember the tag for icon distance but Ticks have it to make them draw as icons before every other unit.

**Comment by lhog** [comment]
It looks so that it's no longer required to suppress engine's unit drawing.
Previously unit model used to clip through icon in some cases, now it doesn't seem to be the case anymore. Thus ecde74e

**Pull request merged**
