### PR TITLE
Get rid of error spam

### PR DESCRIPTION
**Pull request by Arch-Shaman**
Removes all debug echos. Ill take care of the rest in 4-6 days.

### CODE REVIEW

**Comment by Arch-Shaman** [comment]
No idea how to unrevert stuff from web interface on mobile so... >.<

**Comment by GoogleFrog** [comment]
I don't think this would fix the errors.

**Comment by Arch-Shaman** [comment]
Hm. Well I'm 4-6+ days without a test environment. Ill look into the best I can with the environment I have (mobile phone.. web interface, crappy cell reception).

**Comment by Arch-Shaman** [comment]
Yeah I'm still out of commission right now. New apartment doesn't have ethernet ran around the unit so had to get a wireless card. I lack a chair as well at the moment. Eta for solution is in 2-4 days.

Thought i would give an update here.

**Comment by Arch-Shaman** [comment]
see #4088. Dunno how to fix the conflicts, but I figured out what was causing it.

**Pull request closed without merging**
