### PR TITLE
WIP Tank Factory remodel

### PR DESCRIPTION
**Pull request by sprunk**
- [ ] no decal (@Anarchid)
 - [ ] there are normals but I don't know if they work.
 - [x] ~build area still clips underground. Factories built normally (or rezzed, /given etc.) don't flatten ground - only plop does.~ #2533
 - [ ] the pipe on the side has no collisions because `solid_factory` is 1-dimensional. Minor polish thing.

### CODE REVIEW

**Comment by GoogleFrog** [comment]
I do ground decals now, since nobody else seemed capable.

**Comment by GoogleFrog** [comment]
[f=-000001] Error: [LuaRules::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=Initialize trace=[Internal Lua error: Call failure] error = 2, LuaRules/gadgets.lua, [string "LuaRules/Gadgets/mex_spot_finder.lua"]:358: attempt to compare number with string
stack traceback:
	[C]: in function 'Include'
	[string "LuaRules/main.lua"]:32: in main chunk

[f=-000001] Failed to load: api_startboxes.lua  ([string "LuaRules/Utilities/startbox_utilities.lua"]:91: bad argument #1 to 'randomseed' (number expected, got no value))
[f=-000001] Loading last game win data

**Comment by Anarchid** [comment]
What! This PR shouldn't affect either startbox api nor mex spot finder? Did you test on some broken map?

> there are normals but I don't know if they work.

IIRC normal map detection only checks .dds files. Textures will need to be cast to dds.

**Comment by sprunk** [comment]
Presumably needs rebase.

**Comment by sprunk** [comment]
#2610

**Pull request closed without merging**
