### PR TITLE
quick fix for weird TV effect until engine bug is fixed

### PR DESCRIPTION
**Pull request by dvr333**

### CODE REVIEW

**Comment by dvr333** [comment]
It looks like engine 100.0.1 (101RC) can't handle Spring.SetCameraState() without clobbering screen-space drawing.

**Comment by dvr333** [comment]
Engine bug mantised at https://springrts.com/mantis/view.php?id=5075

**Comment by dvr333** [comment]
Apparently the engine bug is fixed, so if the TV problem is gone without needing this PR then don't bother merging.

**Comment by GoogleFrog** [comment]
We'll assume engine fix fixed it.

**Pull request closed without merging**
