### PR TITLE
⚖️ Zenith fire once now fires just 1/3 of meteors

### PR DESCRIPTION
**Pull request by sprunk**
Tries to alleviate the main issue of the unit (which is that meteors past
the first ~30 are mostly useless since everything except Det dies anyway)
without ruining the "firing spends way too much ammo" aspect of the unit.

This is a new mechanical ability for the unit and not just a bit of UI,
unlike Fire Once for other units. This is somewhat important not just
because of efficiency but also because overflow is bad so if you could
send a small, fixed amount of meteors into a corner it would dilute this
penalty.

### CODE REVIEW

**Comment by GoogleFrog** [comment]
So if I'm reading this correctly, a command with the fire-once switch makes it fires all the meteors? If it doesn't fire once by default then I doubt people will discover this ability, so it would take a long time to notice any balance impact. I also find the limit of 1/3 a bit weird.

How about up to 100 meteors at once, and a reload time of something like 5-10s. The reload time would give people a much better chance of noticing the batching. Then fire once would work as normal and the limit of 100 rather than 1/3 would prevent long tails of dregs.

**Comment by sprunk** [comment]
> a command with the fire-once switch makes it fires all the meteors? If it doesn't fire once by default then I doubt people will discover this ability, so it would take a long time to notice any balance impact

Currently fire-once fires 1/3 and default fires all, since I was afraid of messing with the defaults and people's muscle memory (and presuming that nobody fires once at the moment). But since you agree I'll swap it.

> the limit of 100 rather than 1/3 would prevent long tails of dregs

The long tail is the point because it lets you send multiple bursts while making sure they're reasonably large. This maintains how Zenith is about burst damage but removing the "far too much burst damage than is useful" part that is keeping it down.

If you start from 300, then at flat-100 you can shoot 100, 100, 100.
At 1/3 you can shoot 100, 67, 45, 30, 20, 13, (25 remaining). Most of those are still brutal bursts, keeping with Zenith's theme, and enough to destroy most targets, but there are twice as many compared to flat.

If you start from 100 then at flat-100 you can just shoot 100.
At 1/3 you can shoot 34, 22, 15, (29 remaining). Four reasonable bursts instead of one but excessive.

The bursts can still get larger than you may prefer, but this happens slowly as you approach the cap, and you can trim the burst size somewhat gently (by using it). Compare to flat 100 which only ever lets you make one non-excessive burst (depending on how many meteors you have modulo 100).

---

Originally I wanted to make the burst a flat 25, but ultimately decided not to because I thought reaching the cap should still hurt a lot to keep incentivizing usage (and wasting 25 to prevent meteors falling on yourself hurts less than wasting 100) and to be Quant (since other superweapons don't have that kind of downside). Maybe the punishment is another thing keeping Zenith down though so perhaps the flat 25 isn't too bad after all, at least as long as the other supers don't have their own punishments? Idk. If you read this and still think that flat 100 is better (and that this is worth doing over the energy change suggested in #3922) then I'll just do that (in addition to the other changes).

**Comment by GoogleFrog** [comment]
> If you start from 300, then with flat 100 you can shoot 100, 100, 100.
With 1/3 you can shoot 100, 67, 45, 30, 20, 13, (25 remaining). Most of those are still brutal bursts, keeping with Zenith's theme, and enough to destroy most targets, but there are twice as many compared to flat.

 > If you start from 100 then with flat 100 you can just shoot 100.
With 1/3 you can shoot 34, 22, 15, (29 remaining). Four reasonable bursts instead of one but excessive.

To me this implies a really kludgy model of the underlying (ie UI independent) abilities of the unit. The actions that a unit can take should have some level of in-world reasonableness. I see what you're doing UI-wise, but in terms of mechanics this is very complicated and awkwardly close to the much simpler rule: Zenith can fire any number of meteors it likes.

**Comment by sprunk** [comment]
> in terms of mechanics this is very complicated and awkwardly close to the much simpler rule: Zenith can fire any number of meteors it likes.

Is this a suggestion (if yes, is 1 preferable to 100)? I considered making fire once fire just one meteor but decided that this would be un-Quant because this makes the "going over the cap punishes you via meteors fall on your head" that is unique to Zenith obsolete (just send 1 meteor into the corner right before spawning one over the cap) and also because Zenith is all about large bursts.

Maybe with fire 1,  Zenith is still all about bursts because sending 1 meteor is fairly pointless and maybe the punishment doesn't work in practice?

**Comment by GoogleFrog** [comment]
> I considered making fire once fire just one meteor but decided that this would be un-Quant because this makes the "going over the cap punishes you via meteors fall on your head" that is unique to Zenith obsolete

I think any form of partial burst degrades this aspect to the point that the cap punishment may as well be removed. I think the big problem with partial burst is UI, as I don't recall hearing any suggestions that make such a Zenith have a good UI for common tasks.

I'm not sure that I'm at the point of suggestions yet. So far I feel more like I've been finding potential complications down various paths rather than picking a best path.

**Comment by sprunk** [comment]
Keeping the branch, maybe reopen later when Zenith really needs looking at.

**Pull request closed without merging**
