### PR TITLE
Fix for underwater names and icons

### PR DESCRIPTION
**Pull request by dvr333**
Partial fix for #577, though the real fix is engine-side.

EDIT (2014/04/21): Fully fixed with the most recent commits. Engine side fixes only need to worry about unit build wireframe effects.

### CODE REVIEW

**Comment by GoogleFrog** [comment]
Then you can see the icons behind terrain, which is bad.

**Comment by dvr333** [comment]
I don't think this affects unit icons, just state icons, some of which you can already behind terrain.

**Comment by GoogleFrog** [comment]
I meant the state icons. Currently they are blocked by terrain.

**Comment by dvr333** [comment]
In that case, we're dealing with an engine bug (bumprefraction 2 makes water surface have depth value like terrain), and the lobby settings presets shouldn't set bumprefraction to 2.

I still think names should show through terrain.

**Comment by xponen** [comment]
i think this conflict can be resolved by making the fix only activate for underwater unit and under specific settings.
we can read setting like this: Spring.GetConfigInt("bumpwatersettingname"),
and probably detect if its drawn underground/underwater if height is <0

**Comment by dvr333** [comment]
There are other issues with bumprefraction set to 2 and depth testing, both in widgets and in general play, so the only real fix is to the engine, and that means we can't really use that setting in the lobby presets until then.

**Comment by dvr333** [comment]
Finally found a solution that handles water properly. Still not sure how to fix outlines and halos, but everything else works properly.

**Pull request merged**
