### PR TITLE
Use 103 shaders (load perf: no model preloading)

### PR DESCRIPTION
**Pull request by sprunk**
@lhog
@ashdnazg

### CODE REVIEW

**Comment by lhog** [comment]
Yes, `ModelMaterials_103` is apparently older than `ModelMaterials`.

As my monkey with grenade coding approach (i.e. changing something without full understanding of subject matter) didn't work out, I'm wondering if you have any idea how to stay on ModelMaterials code and not have spam below:
```
[f=0002220] Warning: LuaMaterial: incorrect uniform type for "ViewMatrix", got: unknown expected: mat4
[f=0002220] Warning: LuaMaterial: incorrect uniform type for "CameraPos", got: unknown expected: vec3
[f=0002220] Warning: LuaMaterial: incorrect uniform type for "TeamColor", got: unknown expected: vec4
[f=0002220] Warning: LuaMaterial: incorrect uniform type for "ShadowMatrix", got: unknown expected: mat4
[f=0002220] Warning: LuaMaterial: incorrect uniform type for "SunDir", got: unknown expected: vec3
[f=0002220] Warning: LuaMaterial: incorrect uniform type for "ShadowParams", got: unknown expected: vec4
```

Also, if `ModelMaterials_103` is old and we are apparently not going back to 103.0, I think we should remove this folder.

**Comment by GoogleFrog** [comment]
I want compatibility back to 103.0 for benchmarking purposes. A wide range of compatibility has been useful for exactly this in the past.

What is this PR for?

**Comment by ashdnazg** [comment]
For fixing a mistake in a previous PR.
There's another fix needed, I'll probably make another PR later

**Comment by ashdnazg** [comment]
See #2415

**Comment by ashdnazg** [comment]
@lhog the spam should be fixed here: https://github.com/spring/spring/commit/ff0c4ab4adbc09178dc8e0e9750ac60116723549

**Pull request merged**
