### PR TITLE
shieldfac remodel

### PR DESCRIPTION
**Pull request by sprunk**
image

### CODE REVIEW

**Comment by GoogleFrog** [comment]
You should apply it to a different factory since I already hacked the current shield model into compliance.

**Comment by sprunk** [comment]
I'm not sure if it fits any other fac. Not only visually but also the build area is tiny and anything larger than Felon won't fit.

**Comment by GoogleFrog** [comment]
What about the vehicle factory?

**Comment by sprunk** [comment]
Domi and Impaler won't fit the build area.

**Comment by Anarchid** [comment]
Apparently this is now in need of rebase. I added the original decal and texture 2. I did not succeed in applying the tex2 though because that requires Upspring. Attempting to run Upspring on my machine hangs the desktop environment.

The decal is slightly misaligned. This is fine because it's getting replaced with a standardized decal anyway.

image

**Comment by Anarchid** [comment]
The buildicon generator seems to choke on this s3o: 
image

**Comment by GoogleFrog** [comment]
I might want to make some shieldbots 3x3 footprints.

**Comment by sprunk** [comment]
With a model size increase? Footprint itself is probably okay.

**Comment by GoogleFrog** [comment]
Not with a model size increase. Look at a stack of Thugs, they clip and have trouble firing.

**Comment by sprunk** [comment]
I think footprint won't be a problem.

**Comment by GoogleFrog** [comment]
screen00475

**Comment by sprunk** [comment]
Is this picture demonstrating Thug's footprint being too small? I'm not saying "unit footprints are not a problem and their values are fine" but "sure, increase them, the new factory model should handle increased footprint well".

**Comment by sprunk** [comment]
I checked and the remodeled fac can build 3x3 units without needing any change to accomodate them.

**Comment by Anarchid** [comment]
image

**Comment by Anarchid** [comment]
image

**Comment by Anarchid** [comment]
I think this is pretty done aside from the merge conflict.

**Comment by Anarchid** [comment]
image

**Comment by Anarchid** [comment]
Verified upscaled thugs being mass-produced with no issue after rebasing to master. 
image

**Comment by GoogleFrog** [comment]
Can you make the texture better? It looks comparatively grimdark with the dark streaked grey. Also the edges of inner structure are cut off a little weirdly. Perhaps I need to see it at normal zoom.

**Comment by Anarchid** [comment]
I'll try to make it more rainbows-and-unicorns.

**Comment by sprunk** [comment]
I've fixed the merge conflict.

**Comment by Anarchid** [comment]
This version of the model has too small portal, and the model with the portal scaled to adequately house a felon fails to not be uglier than i am willing to commit.

**Comment by sprunk** [comment]
sad!

**Comment by GoogleFrog** [comment]
Portal? You mean the pad that the unit is built on?

**Comment by Anarchid** [comment]
The whole pad / cover / door assembly.

I feel it's better to attempt a new model instead.

**Pull request closed without merging**
