### PR TITLE
add pun

### PR DESCRIPTION
**Pull request by Anarchid**

### CODE REVIEW

**Comment by sprunk** [comment]
Helptext still says laser.

**Comment by sprunk** [comment]
Helptext *still* says laser.

**Comment by sprunk** [comment]
The helptext files live in ./LuaUI/Configs/lang/units.*.json

**Comment by DeinFreund** [comment]
Why is this here?

**Comment by DeinFreund** [comment]
*Umlautsgrammatikskorrektheit

**Pull request closed without merging**
