### PR TITLE
Modstats sends facplop data to Springie

### PR DESCRIPTION
**Pull request by sprunk**
Infra support soon™

### CODE REVIEW

**Comment by Licho1** [comment]
I thought that Anarchid changed this to JSON format...

**Comment by Anarchid** [comment]
The JSON conversion was reverted or disabled because it didn't work. 
Modstats don't just not send faclop data; no data arrives on Springie at all for a while now.

**Comment by Anarchid** [comment]
Related: 
https://github.com/sprunk/Zero-K/commit/73d4d1094e5c8d8a50b57b8a7f8d802d3d651575
https://github.com/sprunk/Zero-K/commit/5d23b41242a7dbfd1d5ba39442f22ed7f02ac355

**Comment by Licho1** [comment]
Unrevert if problem is elsewhere and continue on json path?

**Comment by Anarchid** [comment]
Finding/fixing the gameover issue unlocks unrevert of json path.
Probably wise to first make a stable with pending balance changes/fixes, e.g. for retarded movedef maps.

**Comment by sprunk** [comment]
Will investigate modstats first because that approach is superior

**Pull request closed without merging**
