### PR TITLE
remove "command console activated"

### PR DESCRIPTION
**Pull request by sprunk**
super annoying and useless (gets played halfway through loading)

### CODE REVIEW

**Comment by Licho1** [comment]
Why? If anything it needs more sounds to nofity that game is about start etc. Exlain why. Unless there is a major license problem (its warzone voice so it should not be), keep it

**Comment by sprunk** [comment]
It does not really notify that game is about to start because in Spring 98 pathing is done after widgets are loaded so it fires off when load is at ~60-70% which can mean few minutes of wait when calculating pathing for the first time.

It doesnt respect volume settings (it is played when loading and volume settings might arent loaded yet) and is not togglable.

Most people seem annoyed by it (maybe poll would give good data on this).

**Comment by Anarchid** [comment]
It seems like the proper solution would be to figure out when to start it properly.

**Comment by KingRaptor** [comment]
Move it to loadscreen?

**Comment by Anarchid** [comment]
Does loadscreen know the last instant of loading? Then yes.

**Comment by sprunk** [comment]
Moving to loadscreen sounds sensible and superior to removal.
Closing

**Pull request closed without merging**
