### PR TITLE
Remove sub 95% damage resistance to ground weapons

### PR DESCRIPTION
**Pull request by sprunk**

### CODE REVIEW

**Comment by GoogleFrog** [comment]
Subs are too close to the surface of the water. AoE would deal significant damage.

**Comment by Anarchid** [comment]
Is the option where they lose armor when projected onto dry land by wyvern/terraform/valkyrie an acceptable alternative?

**Comment by GoogleFrog** [comment]
Yes, explain how. UnitPreDamaged?

**Comment by Anarchid** [comment]
I'd go with SetSfxOccupy instead.

**Comment by sprunk** [comment]
Closing (will submit a proper solution shortly)

**Pull request closed without merging**
