### PR TITLE
Cloakbots animations

### PR DESCRIPTION
**Pull request by mvollrath**

### CODE REVIEW

**Comment by mvollrath** [comment]
Here's a [video of the new animations](https://youtu.be/lKbzvkce65E).

**Comment by mvollrath** [comment]
Here's [a video of some more tweaks to Glaive, Ronin, Gremlin, and Phantom animations](https://youtu.be/ZbYt9vVEjIs).  I've added idle animations to Glaive and Gremlin and some other subtle tweaks like being able to lead with either the left or right foot.

**Comment by Anarchid** [comment]
I think thr new glaivr and scythe run cycles leg it a bit too much, skipping the phase where the character has both feet off the ground.

The walk cycles - which is all units except scythe and glaive here - look much inproved.

**Comment by mvollrath** [comment]
Here's [the new Glaive](https://youtu.be/WC-BE9_M_tQ).

**Comment by mvollrath** [comment]
[Had to do the Conjurer too](https://youtu.be/Fje5c4-Cdfg).

**Comment by mvollrath** [comment]
[Video](https://youtu.be/Yv1-wyT4Z0U)

Revise animation scripts for most units in Cloakbot factory.

Overall, I tweaked the animation speeds to match the movement speeds of the units, so they look more natural. There's also new logic to prevent future balance changes (movement speed) from breaking the animation rate.

Many units now have additional motion in their running animations or completely redone animations. Each unit has its own character.

A recurring bug was running animation speed not being affected by movement speed modifiers. Should be fixed for all of them now.

**Comment by GoogleFrog** [comment]
Looks good and I like the style in the code changes. The Glaive is especially improved since the WIP video I saw earlier. You've applied a bit more attention to detail than I have previously used in similar cases, and it is impressive as a weekend of work. I hope to see more things like this, perhaps commanders or striders could be improved.

**Comment by sprunk** [comment]
I really like those as well, CJ!

**Pull request merged**
