### PR TITLE
stockpile obeys disarm

### PR DESCRIPTION
**Pull request by sprunk**

### CODE REVIEW

**Comment by GoogleFrog** [comment]
Screamer?

**Comment by sprunk** [comment]
Stockpile: Screamer & Silencer.

**Comment by GoogleFrog** [comment]
I don't believe you.

**Comment by sprunk** [comment]
...???

**Comment by GoogleFrog** [comment]
Does it interact with priority to communicate the change in drain? It does not look like it does.

**Comment by sprunk** [comment]
https://github.com/sprunk/Zero-K/blob/patch-88/LuaRules/Gadgets/unit_stockpile.lua#L74
disables the drain when disarmed

https://github.com/sprunk/Zero-K/blob/patch-88/LuaRules/Gadgets/unit_stockpile.lua#L58 re-enables the drain when un-disarmed

**Pull request merged**
