### PR TITLE
Quadrupled (configurable) Heavy Tank factory open/close animation speed.

### PR DESCRIPTION
**Pull request by lhog**
Currently it opens/closes very slow and thus delays unit production.

### CODE REVIEW

**Comment by Anarchid** [comment]
HT fac model is getting replaced.

**Comment by lhog** [comment]
Last time I checked HT animation was slowest.
On the topic: feel free to close the PR if not needed.

**Comment by sprunk** [comment]
The animation has to look good and variability between facs is not inherently bad so I'd support a change if the value was an extreme outlier. Having some other facs' values for comparison would be nice.

**Comment by DeinFreund** [comment]
I thought this was long animation intentional to punish my lack of eco awareness.

**Comment by lhog** [comment]
* Spiders, seafac, amphs - almost immediately (<1 sec wait)
* Shields, hovers, cloaky - ~2-3 sec
* Jumps - 3 sec
* GS - 4 sec
* Air, LV - 5 sec
* HT - 8 sec

**Comment by mtroyka** [comment]
why does GS have any wait at all? :|

**Comment by GoogleFrog** [comment]
Is this technically a balance change or not?

**Comment by lhog** [comment]
Not so much a balance change. Rather getting rid of an annoyance.

**Comment by DeinFreund** [comment]
This is very much a balance change, but I think we should aim for simplicity here. Unless there's a good reason for those values, standardization sounds like the way to go.

**Comment by Anarchid** [comment]
I think standardizing fac startup time is not as much a balance change as it is slightly decoupling balance from the whims of crazy artists.

**Pull request merged**
