### PR TITLE
Prevent Locust firing while crashing

### PR DESCRIPTION
**Pull request by a-nop**

### CODE REVIEW

**Comment by a-nop** [comment]
Ick, this is not working yet..

**Comment by a-nop** [comment]
Works now.

**Comment by GoogleFrog** [comment]
Don't all the gunships fire while crashing for the rule of cool?

**Comment by a-nop** [comment]
Locust is under a lot of scrutiny since it dominates on a few MM maps right now.  Free damage seemed like an ok thing to fix.  Maybe it's better to just make some numbers smaller instead.

**Comment by sprunk** [comment]
I wouldn't expect firing while crashing to be a major contributing factor to dominance and I agree that this breaks the rule of cool and consistency with other GS.

**Comment by sprunk** [comment]
Dominance addressed in 7e3755a88d64ddf2da8d56e87d14f13e29060e31

**Pull request closed without merging**
