### PR TITLE
Further clean up of start_unit_setup

### PR DESCRIPTION
**Pull request by Arch-Shaman**
* Removed polling code: This is some remnant from the pre-92.0 days or something. In modern days, it's pretty much pointless to do this as you get it for free from the engine (my guess is it was to stop command locking up or something). 
* Removed the unused variable "gaiaally"

### CODE REVIEW

**Comment by sprunk** [comment]
I have doubts about the CMD.REMOVE thing. It may appear to work correctly on a straightforward test but IIRC the original issue (#2149) was rare.

Try plopping facs in weird spots (uneven terrain, water, terraform in progress by another con?) or other weird circumstances (disarmed commander? change torso turn speed to something low in script and plop behind the comm's back? multiple orders further in the queue, including a second factory in the comm's immediate build radius?) and see if it works correctly without the removal.

**Comment by Arch-Shaman** [comment]
I'll try it out right now.

FWIW, I've had a version of this change live for a few weeks now in FW and haven't seen anything adverse happen. This thing seems like one of those hard to overcome measures.

Case 1: Smooth -> facplop (Seems fine)
image

Case 2: Disarmed commander (actually completes immediately... interesting! This could be fixed by moving facplop to buildstep if it is in fact a bug)
image

Case 3: Another in range factory (Seems fine too)

The current changes are live in future wars and I have not heard of anything regressive going on, but I lack the foot traffic to make a call on this. I could adapt a similar system I use in the current facplop code in FW to the fix and negate some of this. Problem is doing it immediately causes recursion errors occasionally (this is how I took this risk anyways).

**Comment by Arch-Shaman** [comment]
More cleanup: the entire "faction" stuff can be cleaned up as nothing interacts with the system (as far as I can tell) or sends the message. AFAIK is just synonym with customcomm.

**Comment by sprunk** [comment]
The command removal may have been to fix this: https://github.com/ZeroK-RTS/Zero-K/issues/2108#issuecomment-289261012

**Comment by GoogleFrog** [comment]
Disarmed units should not be able to create nanoframes. I recall adding a hax to factory plates to make them unable to do it.

**Comment by sprunk** [comment]
I accepted the unquestionably good part but I am too scared to merge the rest because the original issue was some sort of rare edge case so will not likely be caught by testing.

**Pull request merged**
