### PR TITLE
New model for Archangel

### PR DESCRIPTION
**Pull request by KingRaptor**
Uses a kitbash of Beherith's T1 Core bot models
Much prettier than hunchback!

http://i.imgur.com/gtzkUX3.png

### CODE REVIEW

**Comment by Pxtl** [comment]
Looks great, but I worry it could be mistaken for the Archer.

**Comment by sprunk** [comment]
This is an Archer who changed his gear from Shoulderpads of Dirtbaggery +2 to Cape of Outlawing +3 :P (pretty, but too lookalike imo)

**Comment by GoogleFrog** [comment]
I had to look closely to see how this is not Archer.

**Comment by Licho1** [comment]
Yeah looks like archer :(  Why not use current archangel?

**Comment by KingRaptor** [comment]
Hmm, good point. Less Archery version: http://i.imgur.com/nLp31Hb.png

**Pull request closed without merging**
