### PR TITLE
More interesting award names

### PR DESCRIPTION
**Pull request by sprunk**
Because calling the capture award "Capture Award" is the epitome of boring.

### CODE REVIEW

**Comment by KingRaptor** [comment]
"Apocalypse Bringer" is more... appropriate? Thematic? Something like that - but it also loses the alliteration.

**Comment by GoogleFrog** [comment]
"Dominator" or "Puppetmaster"

"Master Necromancer"

**Comment by sprunk** [comment]
Dominator is a bit broad and so far all the names are multiple words.
Master Necromancer sounds alright but that would be the 3rd thing called "master" already (after puppet and commander).

**Comment by GoogleFrog** [comment]
"Arch Licho"?

**Comment by Orfelius** [comment]
more like "Arch Shaman" :P

**Comment by KingRaptor** [comment]
BTW, is there any particular reason it's "Master of Puppets" instead of just *HoN announcer voice* Puppet Master ?

**Comment by sprunk** [comment]
Mostly because metallica but I don't mind Puppetmaster.

**Pull request merged**
