### PR TITLE
fix #800

### LINKED ISSUE #800: CTF and KoTH doesn't work anymore
Fails to spawn the CTF map points and the KoTH spawn zone (I dont know the details on the issue).

### PR DESCRIPTION
**Pull request by sprunk**

### CODE REVIEW

**Comment by Orfelius** [comment]
What can I say? Looks legit to me!

**Comment by sprunk** [comment]
It prevents confusion because there is actually no working koth/ctf. If somebody wants to have koth/ctf they are free to reimplement but there shouldn't be an option for something that doesn't even work.

**Comment by Orfelius** [comment]
Nono I don't disagree its just quite... I dunno. Interesting to see?

**Comment by sprunk** [comment]
Game-side my implementation is used but infra-side xponen's version got merged.
Both implementations require the counterpart to also get merged to be useful.
Only one version of the shuffer is needed so one of them needs to be chosen and the other reverted.

**Pull request merged**
