### PR TITLE
Remove troll award

### PR DESCRIPTION
**Pull request by sprunk**
No need to reward and showcase troll "achievements".

### CODE REVIEW

**Comment by Licho1** [comment]
why?

**Comment by sprunk** [comment]
Because awards are there to encourage people and reward good play, while troll award rewards teamkilling.

**Comment by Licho1** [comment]
Its not a reward its indicator imo keep it
Dne 11. 4. 2015 2:14 napsal uživatel "sprunk" <notifications@github.com>:

**Comment by sprunk** [comment]
Indicator for whom?

**Comment by Licho1** [comment]
For other players. It's hardly a "reward". We were considering this when it was being added, nothing changed since then.

**Comment by sprunk** [comment]
But teamkill indicator on game over is too late, people already know by then.
Also lobby does not show the award list so it won't indicate anything for the next games.

**Comment by Licho1** [comment]
I'm using it when judging whether to ban someone. Having troll awards increases suspiciousnes of acount.

**Comment by sprunk** [comment]
ok, makes sense

**Pull request closed without merging**
