### PR TITLE
Satisfied GLSL compiler. Should fix https://github.com/ZeroK-RTS/Zero-K/issues/2375

### PR DESCRIPTION
**Pull request by lhog**
Makes me wonder though, why ModelMaterials files are in use and ModelMaterials_103 are not.

### CODE REVIEW

**Comment by ashdnazg** [comment]
103 are the old shaders afaik, some engine changes post 103 were done to fix loading.
After this PR, you should notice how loading times are horrid, as all unit models are loaded before game.

**Comment by lhog** [comment]
It is minimally different to what old Material shader was. I don't have it in front of my eyes, but the differences were mostly look like ```modelpath --> model.path```

**Comment by ashdnazg** [comment]
Indeed.
.model.path was redeprecated because accessing .model forced loading the model (to get info such as mins and maxs).

(So probably, it won't affect loading times, but will just crash)

**Comment by lhog** [comment]
I ran a few Circuit vs Circuit games on that branch.
It worked just fine. No crashes or visual degradation.

Perhaps you can suggest/make changes, that you feel necessary, other than just criticizing.

**Comment by ashdnazg** [comment]
yes, I didn't notice that it checks if modelpath isn't nil.
anyway, re. suggestions:
1) Add the line ```Spring.Echo(udef.name, udef.model.type)``` here: https://github.com/ZeroK-RTS/Zero-K/blob/master/ModelMaterials_103/1_normalmapping.lua#L73 and watch the infolog.
2) Change back to using ModelMaterials and not ModelMaterials_103

**Pull request merged**
