### PR TITLE
BAR style lightning beam example

### PR DESCRIPTION
**Pull request by sprunk**
JUST the beam itself: no CEG, projectile lights may be screwed up as well (my potato doesn't have them so IDK how it looks).
Applied to `tankheavyraider` Blitz (ZK texture + BAR wiggly beam) and `cloakassault` (vanilla engine texture + BAR wiggly beam).

### CODE REVIEW

**Comment by GoogleFrog** [comment]
Just looking at the numbers I'm expecting this to be a nerf vs Glaive.

**Comment by Anarchid** [comment]
> Just looking at the numbers I'm expecting this to be a nerf vs Glaive.

That sounds healthy for cloakassault.

**Comment by sprunk** [comment]
The burst seems to track jinking targets (while maintaining spray angle) so jinking doesn't seem to do as much as it ought to, plus after 4 frames the Glaive gets stunned anyway. The burst also means that overkill can go through and affect multiple Glaives (like eg. Lance does), which does not help pure Knight (because it has perfect damage to kill a Glaive) but may help mixed armies.

Some other effects:
- doing worse at dealing EMP damage, because the earlier instances are dealt to a healthier unit. For example LLT no longer gets stunned on the first shot because `600/(785-230)` > 1 but `60/(785-1*23) + 60/(785-2*23) + ... + 60/(785-10*23)` < 1, though of course the beam could also be made shorter or the damage compensated.
- does worse at piercing shields
- does better at maintaining stun (if EMP ticks down during the burst, some of the later damage will make up for it)

And other thoughts:
 - longer burst means jinky units can just get grazed instead of taking a full hit, but in a large swarm somebody else is likely to take the rest of the hit. This is somewhat similar to inaccuracy. Maybe a KR balance sort of change would be to remove the inaccuracy in compensation.
 - if it's not worth making even minute changes to balance for a visual upgrade then the current behaviour could also be maintained (have the entire damage happen in the 1st frame, the others are just visual). This is doable with Lua, though ideally the engine would just get a weapondef tag that says "reshuffle the lightning wiggle every frame" because that is fundamentally what the burst does.

**Comment by GoogleFrog** [comment]
So much is in the works already that I expect to wait for after the next stable.

**Comment by sprunk** [comment]
Sure, it's just eye candy.

**Comment by sprunk** [comment]
Linking #3900.

**Comment by sprunk** [comment]
Included in #4975

**Pull request closed without merging**
