### PR TITLE
differentiate razor pew

### PR DESCRIPTION
**Pull request by sprunk**
the patch makes razors use a new pew graphic to differentiate the aa-only red pew from the universal pew.

razor

### CODE REVIEW

**Comment by Anarchid** [comment]
Shredder also exists!

**Comment by sprunk** [comment]
both are affected

**Comment by GoogleFrog** [comment]
I don't like the look of it for Razor. This looks more like a bolt of something instead of a pew pew laser. The sound, speed and length differentiation seems like changes are not required.

**Comment by sprunk** [comment]
Would a bolt (the bitmap, not necessarily red and spammy) look good on anything else?

**Comment by Anarchid** [comment]
IMO it looks good on spammy AA lazor and differentiation has utility.

**Comment by sprunk** [comment]
Swift and Krow are both universal pew, not AA pew.

**Comment by KingRaptor** [comment]
I like this but I think the bolts as shown look a bit long.

**Comment by sprunk** [comment]
That is trivial to change; want a bunch of comparison pictures?

**Comment by Pxtl** [comment]
Why not teal to match other AA lasers?  Keep a distinct shape so it doesn't look like the archangel weapon, but otherwise matching up with the jumpy and cloaky as would be good.

**Comment by sprunk** [comment]
I kept red because the shape was differentiating enough and because a colour scheme does not really exist (eg. teal is not AA because LLT).

**Comment by sprunk** [comment]
trimmed pew to 2/3 the size

**Comment by sprunk** [comment]
lack of response; closing

**Pull request closed without merging**
