### PR TITLE
Overwhelming Numerical Advantage for FFAs

### PR DESCRIPTION
**Pull request by sprunk**
Allow Overwhelming Numerical Advantage in FFAs

### CODE REVIEW

**Comment by GoogleFrog** [comment]
I don't think this should be implemented because players with very little can build up while stronger players fight each other.

**Comment by Licho1** [comment]
Value used should be different, like total metal spent so far. You can win without having a single mobile unit in FFA.

**Comment by sprunk** [comment]
Overwhelming Numerical Advantage means there is only one "stronger player" though, and much stronger than everyone else. The value of a single player has to be a multiple of *everyone else's value combined*.

Basically the situation is *even more skewed towards the big guy* than in 2-alliance situation unless all the little guys perfectly cooperate in which case it's the same.

**Comment by db81** [comment]
> players with very little can build up while stronger players fight each other

I think this can be solved with only enabling ONA once there's only a single player supreme over everyone else.

**Comment by sprunk** [comment]
That's what the code does. The value multiplier compares each person's value with the sum of everyone else's.

**Comment by db81** [comment]
Ah, sorry, didn't read before posting.

**Comment by GoogleFrog** [comment]
I still think numerical advantage should not do anything in FFA. Consistency in information is important and there is more room for a swing (due to some sort of assignation).

**Comment by sprunk** [comment]
Alright

**Pull request closed without merging**
