### PR TITLE
Allow wind swaying for all plant-like features ever made for spring

### PR DESCRIPTION
**Pull request by ForbodingAngel**
As well as all features that exist within spring features.

### CODE REVIEW

**Comment by Anarchid** [comment]
This already allows too much features: for example, streetlights on Intersections should definitely **not** sway eldritchly with the wind.

**Comment by ForbodingAngel** [comment]
WTF? Why would streetlights on intersection sway?

`[streetlamp_1]
{
	world=allworld;
	description=Street Lamp;
	object=streetlamp_1.s3o;
	footprintx=1;
	footprintz=1;
	height=36;
	blocking=1;
	hitdensity=5;
	metal=5;
	energy=200;
	damage=40;
	flammable=0;
	reclaimable=1;
	autoreclaimable=1;
	featurereclamate=smudge01;
	seqnamereclamate=tree1reclamate;
	upright=1;
}`

This is the lone featuredef in Intersection v3. Please tell me at what point the name "streetlamp_1" contains any of the following words:

- tree
- bush
- vegetation
- baobob
- aleppo
- pine
- senegal
- palm
- shrub
- bloodthorn
- birch
- maple
- oak
- fern
- grass
- weed
- plant
- palmetto

As you can see, none of those words exist in the name "streetlamp_1", therefore it would not sway.

**Comment by Anarchid** [comment]
The commit and PR are badly worded, but Intersection streetlights swaying is not something i **read** but rather, something i **observed** last time when i played Intersection in ZK.

**Comment by ForbodingAngel** [comment]
Hmm, fair point. If this did category parsing 
```
	category			= "urban",
```
in features rather than name parsing, everything would work better. All the features in SF have categories assigned to them.

**Comment by Anarchid** [comment]
That woild deal with streetlights, but i still fear for cloakbots. Do only Gaia features get sway?

**Comment by ForbodingAngel** [comment]
Well, my thinking is that if it looks in the def for category and filters out anything that isn't in the category  of vegetation (also check for vegitation because some people can't spell :-)), then the problem solves itself, does it not?

**Comment by Anarchid** [comment]
That seems safer in the sense that it extra unlikely to allow non-vegetative things to sway. You could also, at that point, remove the name matching wholesale.

Unsure if there exist "vegetation" category things which shouldn't sway, or vice versa.

**Comment by Anarchid** [comment]
It seems that `category = "vegetation"` things exist as well - beherith's rocks are all "vegetation". So you definitely can't do simple category whitelisting, name matching has to stay...

**Comment by GoogleFrog** [comment]
ZK-side features should be easily excludable. We can add customParams or, if customParams don't exist, put particularly blacklisted substrings in their name.

**Comment by ForbodingAngel** [comment]
The rocks have that category? well fudge me. Ok I'll fix it right now. SF wasn't supposed to be a one person enterprise, but sadly that's the way it turned out. Thanks for letting me know. Feel free to post issues on the tracker on the SF repo if you find other stuff.

**Comment by sprunk** [comment]
>some people can't spell :-)

>baobob

**Comment by ForbodingAngel** [comment]
Touche :-)

**Pull request closed without merging**
