### PR TITLE
Group Stats Graph Buttons

### PR DESCRIPTION
**Pull request by CrazyEddieTK**
Allows for stats to be grouped together, and displays the groups simply but nicely in the graph UI.

### CODE REVIEW

**Comment by CrazyEddieTK** [comment]
new-button-layout

**Comment by CrazyEddieTK** [comment]
If my midgame-toggle PR is accepted, there will need to be a few changes to merge with this one, since this one changes the relationship between the buttons and their ancestor objects.

**Comment by sprunk** [comment]
Merge conflict. Also, I'd put the damage ones under Units (since damage concerns units).

**Comment by CrazyEddieTK** [comment]
Hmm??

image

> Also, I'd put the damage ones under Units (since damage concerns units).

Done.

**Pull request merged**
