### PR TITLE
fix Alt+mex terraform not working

### PR DESCRIPTION
**Pull request by xponen**
This address issue https://github.com/ZeroK-RTS/Zero-K/issues/562

Changes:
  - I moved "PlacingRectangle" code into "widget:CommandNotify()" (in gui_lasso_terraform.lua widget). This immediately fix https://github.com/ZeroK-RTS/Zero-K/issues/562

  - I made WG.Terraform_SetPlacingRectangle() to be defined at widget:Initialize() because defining WG. function outside widget:xxxxx() function will broke local copy of same widget due to conflict problem!**

  - also, I had to modify stuff in cawidget.lua to make  "CommandNotifyMex()" event work with multiple widgets (the event from cmd_mex_placement.lua being used by both terraform and CBAI widget to read mex placement).

  - additionally (minor) I tweaked CBAI widget to recognize the build-queue produced by "structure on terraform", so cons will assist the queued buildings.

I tested locally and fully satisfied with the result, 
**Unfortunately I couldn't use local gui_lasso_terraform.lua in ZK:stable MP because of the WG. conflict. However I'm 100% sure it worked.

### CODE REVIEW

**Comment by GoogleFrog** [comment]
Too complicated. Why the CBAI and especially why the widget handler changes?

**Comment by Licho1** [comment]
Imo it needs more rethink.
What i suggested is to make it work like this:
With structure to be placed selected, hold mouse to enter "height mode"
adjust height, when mouse is released, both terra and structure are queued.

This should listen to stanard modifiers (shift, space etc) for adding/inserting into queue.

This will also make it work with gesture menu and mexes.

If you provide simple API it could also be used by CBAI

**Comment by xponen** [comment]
@GoogleFrog I fixed issue #562 by adding a global function in gui_lasso_terraform ("CommandNotifyMex") which is called from cmd_mex_placement. Unfortunately I can't add 2 global function with same name :( this is bad for CBAI widget 

So I modify the cawidget.lua to allow adding 2 or more global function with same name! 
It seem okay. I can definitely test in regular game and see if it is wrong.

**Comment by xponen** [comment]
@Licho1 I only fix 1 case (terraform mex placement), so I wasn't touching the key shortcut.

But, since I moved "structure on terraform" code into engine's "widget:CommandNotify()" it now able to read SHIFT& ALT, so if @GoogleFrog  make it obey SHIFT & ALT then we can make like... a wall of spikes for example :P

CBAI only assist buildings, not terraform (CBAI is just constructor assisting other constructor and split queue)

**Comment by Anarchid** [comment]
Mousedrag altude change would be interesting as an UI option. 
I still don't know how to use the current one, i tried a few times and always failed.

**Comment by xponen** [comment]
@Licho1 and @Anarchid ,the suggestion to change key shortcut need to be in dedicated issue, this PR just fix ALT+ mex_placement_terraform,

although complicated, its just fixed that thing.

**Comment by xponen** [comment]
@Licho1 , I could add the mex terraform shortcut to any build menu widget. will do in other PR

**Comment by Anarchid** [comment]
> this PR just fix ALT+ mex_placement_terraform and will be closed upon PULL

Wouldn't the drag-terraform *circumvent* it and make that fix unnecessary?

**Comment by xponen** [comment]
@Anarchid , you mean, don't need alt+structure_terraform at all because can do manually?
IMO, doing the alt+structure_terraform right have potential in future, its a step toward where you could terraform grid and stuff, although its still not able to do that, but this is 1 step closer.

anyway, somehow this version broke! I must have changed something before Push and broke it... :/

**Comment by Anarchid** [comment]
> you mean, don't need alt+structure_terraform at all because can do manually?

No: i mean that a better UI could be had instead. However, i now realize that just dragging the build option wouldn't help because shift already uses it to draw lines.

**Comment by xponen** [comment]
@Anarchid  the widget is terribly complex, too much global variable... only @GoogleFrog should reinvent the terraform User Interface.

**Comment by Licho1** [comment]
Dragging helps its simple. Hold with mouse still (with lmb) when placing to
enter height mode (after say 0.5).
Its distinct from drag to draw line of structures.

2015-03-05 17:53 GMT+01:00 xponen <notifications@github.com>:

**Comment by xponen** [comment]
merged for the fix only

**Pull request merged**
