### PR TITLE
Hide minimap in tab mode

### LINKED ISSUE #553: When zooming out with tab, minimap does not hide itself (nvidia gtx 970)
http://i.imgur.com/OW8MlyT.jpg

### PR DESCRIPTION
**Pull request by kaen**
Closes #553 

Not sure what mode == 7 referred to originally, but I tested this against all of the camera options. LMK if this is not the right way to solve the problem.

### CODE REVIEW

**Comment by dvr333** [comment]
This should happen on any zoom-out. this solution is okay, but hacky, but the existing setup with COFC and transparency should be extended to apply to any camera (line 830 of gui_chili_minimap). That assumes that the maximum zoom distance of any camera is something Lua can know.

**Comment by sprunk** [comment]
Tab is not guaranteed to be the hotkey for the "tab mode" so it might be a good idea to check for the constant instead of the key.

In future engines the constant will become 5 (not 7).

**Comment by dvr333** [comment]
Mode as a check is far more complicated, if for nothing besides 91 compat. Name seems to be more consistent between engines.

**Comment by kaen** [comment]
cool, thanks!

**Pull request closed without merging**
