### PR TITLE
EMP, Disarm and Slow now affect morphing speed and resource drain. Also partially fixes morph/transport interaction.

### LINKED ISSUE #1667: Morph is not hindered by status effects
EMP and disarm do not halt morph progress. Slow does not reduce morph BP. Ideally these things should affect morph.

### PR DESCRIPTION
**Pull request by Aquanim**
Fixes #1667. I have tested this but somebody else should probably check before this makes it into a stable.

### CODE REVIEW

**Comment by sprunk** [comment]
Looks legit. How does this work with transports (they apply a form of stun but not EMP)?

**Comment by Aquanim** [comment]
That would be why I needed somebody else to check... I didn't think of all the edge cases. One moment.

**Comment by sprunk** [comment]
Transports already break current morph so having them work would be more of a bonus than a requirement.

**Comment by Aquanim** [comment]
Yes, from the outcomes of what I've tried so far "I'll fix that" was a bit over-optimistic, at least as far as tonight is concerned.

**Comment by Aquanim** [comment]
Okay, this now _really_ needs testing to check stupid transporter edge cases.

From the commit:
Units do not complete the morph until they disembark to avoid problems if the target morph is no longer transportable.
(Commandeer morph cannot be cancelled on a Surfboard but I think that's a minor bug.)

**Comment by Aquanim** [comment]
I believe that these commits now satisfy the requirements of #1667, as well as fixing some interactions with transports.

- Units morph slower and drain less resources when slowed.
- Units stop making progress on their morph when stunned or disarmed.
- Units can still cancel morph and refund resources when stunned or disarmed (this is consistent with behaviour of stunned factories).
- Combat morphs may occur normally on a fireplatform transport. Combat morphs on a non-fireplatform transport will be paused. Non-combat morphs on any transport will be cancelled. Morphs on transports can be cancelled by the user.
- A morphing unit which is fully stunned then brought aboard a fireplatform transport will continue to morph; this is a subset of #1687 and I do not think it is appropriate to address here.

**Pull request merged**
