### PR TITLE
Use the nicer smoke.

### PR DESCRIPTION
**Pull request by sprunk**

### CODE REVIEW

**Comment by GoogleFrog** [comment]
This smoke uses a more complicated callin than emitSfx and also makes the unit look like it is on fire.

**Comment by sprunk** [comment]
alright

**Comment by GoogleFrog** [comment]
Perhaps it can be used for units on fire if it's nicer than Lups? I am not sure if it is though.

**Comment by sprunk** [comment]
I prefer the Lups fire too.

**Pull request closed without merging**
