### PR TITLE
Add CMD_PUSH_PULL + icons

### PR DESCRIPTION
**Pull request by ashdnazg**
I've kept the underlying on/off since I didn't want to touch unit scripts, especially when newton still uses bos/cob.

Changes without whitespace: https://github.com/ZeroK-RTS/Zero-K/pull/2560/files?w=1

#1018

### CODE REVIEW

**Comment by GoogleFrog** [comment]
Why the colour change though?

**Comment by ashdnazg** [comment]
to make it the same colour of the icon

**Comment by sprunk** [comment]
I think the old colour pair was nice because it was unique (this looks a bit like heatray and mace?), possibly better to recolour the icons?

**Comment by ashdnazg** [comment]
removed colour change

**Comment by GoogleFrog** [comment]
There are a few lingering questions/issues but they are independent enough that I am happy with leaving this PR as is. If the issues are not addressed by the time I have a bit of free time I will pull the PR and fix them myself. Here is a list:
 * The name "Push / Pull (state)" is insufficiently descriptive. When I redid state tooltips my design was to give the command itself a name independent of the current state because the current state now occurs in the parenthesis. I would call the command "Impulse Mode" or "Gravity Mode".
 * Initial unit states seems to be unchanged in this commit, unless the widget gained some powerful parsing abilities. Sumo and Newton should have their On/Off state replaced with this command in initial unit states.
 * I recall that both players and widgets are unable to toggle On/Off for nanoframes, this makes the initial unit states widget a bit annoying. Testing on nanoframes is required. Potentially this gadget needs a workaround which applies the correct on/off to

**Pull request merged**
