### PR TITLE
More lenient noHotkey

### PR DESCRIPTION
**Pull request by sprunk**
Incentives: hotkeyability generally makes the menu look very messy (the button just fits the hotkey text but is still fairly large, this stretches the layout; it also displaces the checkbox/radiobutton) and not thought out ("why can you even set a hotkey for colorblind mode?"). Trying to remove a hotkey for a menu option and getting negative response from people can also signal UI failure - for example if you need to frequently toggle a menu option then probably it should just have a "active only on SHIFT held" mode or such. If someone really, really wants to bind a hotkey to some obscure function then we can consider them to be an advanced user and ask them to do it the hard way via zk_keys, rather than cluttering up the menu system. See also: #494.

--------

No hotkey for graphical settings. These are pretty much constant. Somebody could in theory try to manually lower the settings as the game gets laggy but any single option wouldn't do much; the proper way to handle that would either be a "general quality" setting that applies these in bulk or for the game itself to adjust it dynamically.
 * Shiny units (advunitshading)
 * Smoothly fade out projectile lights after they explode.
 
No hotkey for preferences that I think generally stay constant:
 * number/anvils as mex income representation
 * Radar color presets
 * square/rectangular pictures in selection window
 * whether to combine units of same type even before selection window is filled
 * whether to filter out OpenGL logs from chat.
 * whether to show group info on the side of selection window.
 * whether overlapping parts of grid circles are drawn twice over
 * color-blindness stuff.

No hotkey for meta-toggles for auto-toggling. If you want to fine-tune toggling then might as well hotkey the toggle itself, not the meta-toggle that controls auto-toggling.
 * meta-toggle on whether backlog / backlog-arrow auto-toggle themselves when chatting
 * meta-toggle on whether heightmap/pathmap toggle themselves when terraform/move command is active
 * meta-toggle on whether projectile lights toggle themselves off when FPS is low

No hotkey for misc things, with comments:
 * whether selection filtering is ignored unless ALT. The whole setting is pretty much "hold a key to temporarily disable" so I have no idea why someone would rather toggle the option rather than just hold ALT.
 * whether to use selection filtering in the first place. Since the ALT option exists it's effectively the same as above.
 * toggle healthbars. Actually still hotkeyable because of duplicate functionality, provided by engine /showhealthbars (bound by default to F9).
 * team colour config. Available through the global commands bar easily enough if someone needs it. I'm unsure on whether it should actually live in the bar because it's a preference that stays constant but that warrants noHotkey as well.
 * whether to draw eco circle for powerplants in queue if a powerplant blueprint is the active command. Already requires SHIFT to show the queue so nobody is going to also manually toggle this.

--------

In comparison to previous commit, the following are kept hotkeyable because it sounds legit to only want them sometimes:
 * show ally selected units.
 * show ally retreat zones.
 * show all commands.
However I think this signals an UI failure; they could instead get an "only show when SHIFT held" option (or a new mode for show all commands).

Misc things kept with comments:
 * whether mex circles use color of (owner team) or (first team of owner's allyteam). It's pretty much simplecolors for mexes so the whole setting should just be removed and obey regular simplecolors.
 * hide ally chat (points, labels). Regardless of hotkeyability I think being able to halt all allychat a priori is harmful for cooperation. Possibly remove the option and provide mute feature.
 * hide spec chat. Under current spec system it's legit and whether specs should be able to talk in the first place is a different issue.

### CODE REVIEW

**Comment by GoogleFrog** [comment]
> How are you using show all commands? I think if you have the need to switch then it probably just warrants a new mode (that you could sit permanently on).

I have Show All Commands/Show On Shift/Show None bound to Ctrl+Shift+Alt (P/[/]). Sometimes I'll use it for switching in spectating and for screenshots. I often use the hotkey to reenable show all commands when playing.

I don't see much of a negative to such hotkeys. If you're testing out settings it is useful to be able to quickly toggle between options.

**Comment by sprunk** [comment]
>I have Show All Commands/Show On Shift/Show None bound to Ctrl+Shift+Alt (P/[/]). Sometimes I'll use it for switching in spectating and for screenshots. I often use the hotkey to reenable show all commands when playing.

Fair enough. I think the optimal solution here is separating the setting for playing and for spectating.

>If you're testing out settings it is useful to be able to quickly toggle between options.

For "testing" as in when creating a new option then sure, have it hotkeyable for a period of time (but not forever).

For "testing" as in people discovering what the options do I think most wouldn't micro-optimize their time with a hotkey and would just manually toggle them (especially since currently radio-buttons can only have keys bound to setting specific values and not to cycling between them).

>I don't see much of a negative to such hotkeys.

I think checkbox and radiobutton menu options shouldn't in general have hotkeys. If needed, they should instead have an option to make a modifier do things.

For example Show All Commands has five states but in theory just three would be sufficient: Show All - Show Selected - Show None; with people binding a hotkey to toggle between them the way they currently use shift. I think this is worse than having the extra options that use a modifier key.

**Comment by GoogleFrog** [comment]
There is a big difference between toggling and holding to enable. You can't add extra options to encompass all the hotkeys people might want. So far the only negative to hotkeyability that I have heard is menu clutter. The "None" hotkey button could be made smaller if that is really your concern.

**Comment by sprunk** [comment]
Alright. Since there is disagreement and the issue is minor this is becoming a bike shed so I think skim through the changes, pick the ones you agree with and let's ignore the others (later fixing their clutter through reducing the hotkey button size or somesuch).

**Comment by GoogleFrog** [comment]
I like to toggle things during the game to test UI, performance etc... This is a rare usage but I don't think the costs are high.

**Pull request closed without merging**
