### PR TITLE
i-cons

### PR DESCRIPTION
**Pull request by sprunk**
cons get icons that reflect their factory

### CODE REVIEW

**Comment by Skasi** [comment]
Back when I made them in 2011 people complained the icons looked like they were prisoners...
evennewericonz

**Comment by Licho1** [comment]
Why is it "M" anyway? Who designed it that way? Me?
It could be W for worker instead.

**Comment by KingRaptor** [comment]
It's an M because I based the original icon set off [this](http://en.wikipedia.org/wiki/NATO_Military_Symbols_for_Land_Based_Systems).

**Comment by sprunk** [comment]
Skasi yours look like prisoners because they are off scale. The M is way too large compared to the backgrounds and is also a bit too high. Compare to mine

**Pull request merged**
