### PR TITLE
Fix #1675 - factory decals have OTA logos.

### LINKED ISSUE #1675: All factory ground decals have TA logos

### PR DESCRIPTION
**Pull request by sprunk**
screen00072
screen00073

### CODE REVIEW

**Comment by GoogleFrog** [comment]
I think there are too problems:
 * They are too bright, they look like a halo around the factories. Ground decals are supposed to be background.
 * They are the wrong scale. The metal plates are large and have a very visible and large grain. This texture does not fix with the implied scale of anything else (maps, factory models etc..).

**Comment by sprunk** [comment]
Do you think darkening the texture and applying a blur (to get rid of visible grain) would do the trick?

**Comment by GoogleFrog** [comment]
I don't know. The metal panels themselves are quite large and still give the impression of smallness. I also just noticed that the textures have a reflection baked into them which makes them look a bit fake.

**Comment by GoogleFrog** [comment]
It is worth a try though.

**Comment by sprunk** [comment]
facs_take_2

facs_take_2a

**Comment by mtroyka** [comment]
yeah that really doesn't look very good. :|

**Comment by GoogleFrog** [comment]
It is hard to tell without advmodelshading.

**Comment by Licho1** [comment]
It also seems to be missing AO plate shadow

**Comment by sprunk** [comment]
Advmodelshading causes models to be invisible for me.

I don't know how to generate the shadow.

**Comment by sprunk** [comment]
Will add proper decals to #2290

**Pull request closed without merging**
