### PR TITLE
remove "i choose you pikachu" spam

### PR DESCRIPTION
**Pull request by sprunk**

### CODE REVIEW

**Comment by Licho1** [comment]
I like comedic aspect of this. Voting against merge..
Don't want ZK to become sterile, serious environment...

**Comment by GoogleFrog** [comment]
I should go to chat. Just not TTS.

**Comment by sprunk** [comment]
What's the point of spamming the chat with info nobody cares about?

**Comment by Licho1** [comment]
Nobody cares? If nobody cares why people spend time/energy inventing original/fun names?
You should speak for yourself . .you don't like them, others apparently do..  Personally I like to listen to fun names...

**Comment by GoogleFrog** [comment]
I care if I am on a team or spectating someone with comm names I know. It can be useful and is not harmful when just sitting in the chat.

**Comment by Licho1** [comment]
Ok i will block it from TTS

**Pull request closed without merging**
