### PR TITLE
WIP: LV remodel with animation

### PR DESCRIPTION
**Pull request by Anarchid**
LV remodel.  Mainly i don't understand why this doesn't generate any nanoclouds from the nozzles despite pieces existing and the stuff being properly built, so if anyone can look into that and find me failure, that would be prim. I also noticed this happening to Sprung's implementation of shieldfac, so perhaps there's something in common. But his was s3o and mine is dae, so it probably is not model geometry? Is there some external LUPS config file for these?

Other todo:

- [x] rotate and upscale so that construction happens sideways and units leave pad along arrows
- [ ] convert some yellow into teamcolor
- [ ] adjust footprint to be wider but narrower and respect yard modifications
- [ ] convert textures to dds
- [ ] figure out if normals are loading and whether they need flipping because dds
- [x] make animations much slower
- [ ] concoct a decal 
- [x] brew a death clone
- [ ] adjust colvol
- [ ] adjust radius
- [ ] check if buildprogress works properly (as buildee)

### CODE REVIEW

**Comment by Anarchid** [comment]
image

**Comment by CrazyEddieTK** [comment]
sexaaay

**Comment by Anarchid** [comment]
I think i've found the issue with nanos for both this and shieldfac in the other thread. It's [the gadget](https://github.com/ZeroK-RTS/Zero-K/blob/173e65a95d5800ed9c6653e249819e872092feed/LuaRules/Gadgets/unit_setnanopiece.lua) which sets nanopieces for cob units and is bound by unit name - incorrectly setting old hardwired nano piece names for these units.

**Comment by GoogleFrog** [comment]
If it's going to take you weeks to aoplane, ground decal, footprint and colvol then I can do them instead.

**Comment by Anarchid** [comment]
That would be good. I'll do stuff tomorrow (i think rescaling, animations, and wreck), but it looks like i won't have the time during the work week.

**Comment by Anarchid** [comment]
I tried to rescale the model to fit the current footprint. It doesn't look good, i think. Better to modify the footprint; if cloaky and shield could gain some elmos, then LV should be good as well. 

image

**Comment by Anarchid** [comment]
image

Kill script is a placeholder.

I think the artsy bits aside from decal are pretty much done here. If this looks okay to the powers that be, i'll proceed to decal / footprint / colvols / etc after fixing close aim.

**Comment by GoogleFrog** [comment]
This PR breaks everything.

[f=-000001] Loading GameData Definitions
[f=-000001] Loading UnitDefs_posts
[f=-000001] [unitdefs.lua] Error: removed the "factoryveh" entry from the "dynassault5_00" build menu
[f=-000001] Loading FeatureDefs_posts
[f=-000001] Loading WeaponDefs_posts
...
[f=-000001] Synced LuaRules: starting loading
[f=-000001] [gadgets.lua] Error: Failed to load: ai_cai.lua  (error = 2, LuaRules/Configs/cai/general.lua, error = 2, LuaRules/Configs/CAI/buildtasks.lua, [string "LuaRules/Configs/CAI/buildtasks.lua"]:37: attempt to index field 'factoryveh' (a nil value))
[f=-000001] [gadgets.lua] Error: Failed to load: unit_factory_guard.lua  ([string "LuaRules/Gadgets/unit_factory_guard.lua"]:57: attempt to index field 'factoryveh' (a nil value))
[f=-000001] Error: [LuaRules::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=Initialize trace=[Internal Lua error: Call failure] error = 2, LuaRules/gadgets.lua, [string "LuaRules/Gadgets/mex_spot_finder.lua"]:358: attempt to compare number with string
stack traceback:
	[C]: in function 'Include'
...

**Comment by KingRaptor** [comment]
It stealth renames `factoryveh` to `factoryrover` (see the end of factoryveh.lua).

**Comment by GoogleFrog** [comment]
Not even that fixes it.

**Comment by GoogleFrog** [comment]
What is this? I change the stealth rename and luarules still fails to load. Then I spawn the unit and it still uses the old model!! Fix your stuff @Anarchid!!!

**Comment by Anarchid** [comment]
The rename was to be able to view the models alongside since the PR is WIP. Old model on `factoryveh` after you "fixed" it is presumably because you did not remove the other file and it overwrote the unitdef.

**Comment by GoogleFrog** [comment]
Then we are at an impasse because I don't want to expend this effort on shield.

**Comment by Anarchid** [comment]
This should fix the unitdef. I've actually failed to commit the proper one, it was in `factoryrover` but with `factoryveh` unitname. 

I guess i can finish LV first. I hope this doesn't mean shield ends up unmerged forever.

**Comment by GoogleFrog** [comment]
You should be able to test whether it is fixed. I don't want to be your build verifyer!

[f=-000001] Loading LuaRules
[f=-000001] Synced LuaRules: starting loading
[f=-000001] [gadgets.lua] Error: Failed to load: ai_cai.lua  (error = 2, LuaRules/Configs/cai/general.lua, error = 2, LuaRules/Configs/CAI/buildtasks.lua, [string "LuaRules/Configs/CAI/buildtasks.lua"]:37: attempt to index field 'factoryveh' (a nil value))
[f=-000001] [gadgets.lua] Error: Failed to load: unit_factory_guard.lua  ([string "LuaRules/Gadgets/unit_factory_guard.lua"]:57: attempt to index field 'factoryveh' (a nil value))
[f=-000001] Error: [LuaRules::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=Initialize trace=[Internal Lua error: Call failure] error = 2, LuaRules/gadgets.lua, [string "LuaRules/Gadgets/mex_spot_finder.lua"]:358: attempt to compare number with string
stack traceback:
	[C]: in function 'Include'
	[string "LuaRules/main.lua"]:32: in main chunk
[f=-000001] Unsynced LuaRules: starting loading
[f=-000001] [gadgets.lua] Error: Failed to load: ai_cai.lua  (error = 2, LuaRules/Configs/cai/general.lua, error = 2, LuaRules/Configs/CAI/buildtasks.lua, [string "LuaRules/Configs/CAI/buildtasks.lua"]:37: attempt to index field 'factoryveh' (a nil value))
[f=-000001] [Modular Comm Info] Warning: Modular Comms API warning: Comm data entry in modoption is empty or in invalid format

[f=-000001] Loading Skirmish AIs
[f=-000001] [Game::LoadGame][6] globalQuit=0 forcedQuit=0
[f=-000001] [cawidgets.lua] Error: Error in CommandsChanged(): [string "LuaUI/Widgets/unit_initial_queue.lua"]:615: attempt to index field '?' (a nil value)
[f=-000001] [cawidgets.lua] Error: Removed widget: Initial Queue ZK
[f=-000001] Mex Placement Initialised with metal map mode.
[f=-000001] SetLobbyButtonEnabled, false
[f=-000001] UpdateInterfacePreset, minimapRight
[f=-000001] [cawidgets.lua] Error: Error in GameSetup(): [string "LuaRules/Utilities/startbox_utilities.lua"]:226: bad argument #1 to 'randomseed' (number expected, got no value)
[f=-000001] [cawidgets.lua] Error: Removed widget: Start Point Remover & Comm Selector
[f=-000001] GameID: d210f75982bb0324c8d705edf0b5e4bc

**Comment by Anarchid** [comment]
Closing PR to replace the branch because of git being complicated.

**Comment by sprunk** [comment]
`git push --force`?

**Comment by Anarchid** [comment]
This was force-push. Doesn't fix *everything*. Superceded by #2590.

**Pull request closed without merging**
