### PR TITLE
Re-organize resource bar tool-tips and economy advice line

### LINKED ISSUE #4081: [Feature] Overdrive 'status' display?
I recently discovered on the wiki that the colours in the economy display mean something - 

If a grid is pink or violet—Make sure you have some excess energy and connect Metal Extractors and energy structures together.

If a grid is light blue or green—Keep adding energy.

If a grid is yellow or red—The grid is inefficient. Spread out the energy by expanding the grid to connect more Metal Extractors.

I feel this is not really all that apparent and it is hard to remember all those colours. Do you think it would be helpful to have something under the little economy display that comes up when you hover over the energy info on the top bar that would give a short 'status' update? 
E.G. Expand Energy production
I've been a long time player and have always wanted to contribute somehow to zero-k maybe a small task like this could be a good way to start? I'm just looking for thoughts on whether or not this would be a useful thing or if its something that just I want.

### PR DESCRIPTION
**Pull request by Sharkgamedev**
Re-organizing of the resource bar hover tool-tips (Both metal and energy) and addition of an economy advice line on energy tooltip.

Fixes #4081

Energy Tooltip:
image

Metal Tooltip:
image

### CODE REVIEW

**Comment by Arch-Shaman** [comment]
Hi and welcome! Just a helpful hint: you can use the keyword `fixes #` (ie: fixes #4081) to automatically close issues. This will link the issue to this pr and automatically close it when it is merged.

**Comment by GoogleFrog** [comment]
> Alright the pull request is ready for review (If I did it right) would it make sense to also do this for the metal toooltip for consistency?

I would like the metal tooltip to have the same indentation style and ordering as the energy tooltip. As far as I recall none of the entries of the metal tooltip need modifying, just the style. It may as well be part of the same PR.

**Comment by Sharkgamedev** [comment]
@Arch-Shaman Thanks for the info! I changed the keyword to fixes as you suggested.

And the metal tooltip has been re-organized as well, although I was not sure where 'unit value' and 'ongoing project value' fit so I just put them under an 'Other' category.

**Comment by Sharkgamedev** [comment]
> > Alright the pull request is ready for review (If I did it right) would it make sense to also do this for the metal toooltip for consistency?
> 
> I would like the metal tooltip to have the same indentation style and ordering as the energy tooltip. As far as I recall none of the entries of the metal tooltip need modifying, just the style. It may as well be part of the same PR.

Was there something else that I needed to do? I noticed it still says '1 linked issue on Github' or is it something an admin has to do? In which case sorry for bugging...

**Comment by Arch-Shaman** [comment]
You just need to wait for it to get merged is all.

**Comment by Sharkgamedev** [comment]
> You just need to wait for it to get merged is all.

Ok thanks a bunch for the reply! Just wanted to make sure their was nothing else I had to do on my end.

**Comment by Arch-Shaman** [comment]
Looks like it's just waiting for a re-review. Time to go work on other projects 😄

**Pull request merged**
