### PR TITLE
Probably fix the range multiplier modoption for raid defense structur…

### PR DESCRIPTION
**Pull request by Sgathec**
…es by changing the camel case modoption key style to an underscore-separated one

### CODE REVIEW

**Comment by Sgathec** [comment]
How does one test modoptions fully beforehand? Using spring.exe doesn't reveal all possible bugs.

**Comment by GoogleFrog** [comment]
You can host dev in springie by doing !game zk:dev.

**Comment by Sgathec** [comment]
Sadly that doesn't help either in this case because I think the lobby client doesn't recognize the new modoption key.

**Comment by GoogleFrog** [comment]
That requires a dev version of the lobby. You can test is multiplayer by setting the key with the !command without using the lobby UI.

**Comment by Sgathec** [comment]
I just did it again because I wasn't certain if I did it properly the last time. After setting the room to zk:dev, I tested using !setoptions and neither the old key nor the new one functioned. Are you sure this method works?

**Comment by sprunk** [comment]
Setoptions probably fails since Springie does not actually have the mod so does not know the modoption. IMO just call it defenserangemult and be done with it.

**Pull request merged**
