### PR TITLE
Blind attempt fix at recursion

### PR DESCRIPTION
**Pull request by Arch-Shaman**
Saw this global set in other examples, so I think it may be a solution. I'm not entirely sure. Plus this stuff is hard to track to see if it fixes stuff. See commentary here: https://discordapp.com/channels/278805140708786177/278908415756206080/845882330300284938

### CODE REVIEW

**Comment by Arch-Shaman** [comment]
Attempts to address https://github.com/ZeroK-RTS/Zero-K/issues/4229

**Comment by GoogleFrog** [comment]
I don't see why this would do anything to that crash report. I think what you need is a recursion check that prevents don't fire at radar issuing the command if it is within another order, as indicated by GG.recursion_GiveOrderToUnit.

**Comment by sprunk** [comment]
I think the blindfix to that issue would rather look like 6fad995f12f9445e11ff26a329e9a3a3f0793ead

**Comment by sprunk** [comment]
Not the correct fix, as mentioned above.

**Pull request closed without merging**
