### PR TITLE
DRAFT: Economy Panel: Various experiments

### PR DESCRIPTION
**Pull request by esainane**
Do not merge!

This is here to make it easier to request broader feedback,
and so that it is not lost.

The major change is a large "Usage" indicator in the middle
of the panel, which can indicate problems much earlier than
the current warnings system, and indicate the extent of
the problem.

### CODE REVIEW

**Comment by esainane** [comment]
preview

**Comment by AshleyMoni** [comment]
This looks really really cool, and I'd love to see this in the main game.

**Comment by GoogleFrog** [comment]
Two forms of usage percent (I'm not sure which is used here) are availible in the base game under economy in hud panels.

**Comment by sprunk** [comment]
Old, draft, and has merge conflicts. Pushed upstream to `eco-panel-experiments` branch so it doesn't get lost https://github.com/ZeroK-RTS/Zero-K/tree/eco-panel-experiments Reopen if there's any progress.

**Pull request closed without merging**
