### PR TITLE
"Exit to Desktop" does not cause resign

### PR DESCRIPTION
**Pull request by sprunk**
See http://zero-k.info/Forum/Thread/20014

### CODE REVIEW

**Comment by Licho1** [comment]
Imo menu should be specific about this option "resign and exit to desktop"
or something like that

**Comment by sprunk** [comment]
Sometimes people want to exit without resign, for example because something is bugged and needs restart.

**Comment by mojjj** [comment]
or ragequit -.-

**Comment by Licho1** [comment]
I guess that if auto AFK kicks in instantly after exit this is fine..

**Comment by GoogleFrog** [comment]
"I guess that if auto AFK kicks in instantly after exit this is fine.."

This was done because auto AFK no longer kills teams.

**Comment by Licho1** [comment]
I mean if AFK transfer happens instantly, which it does so all is fine.

**Pull request merged**
