### PR TITLE
Change Evolved button colours to fit less transparent panels

### PR DESCRIPTION
**Pull request by dvr333**
Possible fix for #1892

### CODE REVIEW

**Comment by GoogleFrog** [comment]
Border color darker?

**Comment by dvr333** [comment]
It seems to provide a bit of a contrast within the button itself, but I'm not entirely sure how that parameter works.

**Comment by GoogleFrog** [comment]
Border color is for the foreground image. There are two images for the button.

**Comment by dvr333** [comment]
Is that a major problem going forward, or is having it look visible on something bright and against a less transparent panel good regardless of how it gets there?

**Pull request merged**
