### PR TITLE
Support scancodes and engine passed actions

### PR DESCRIPTION
**Pull request by badosu**

### CODE REVIEW

**Comment by badosu** [comment]
Closed for lack of review

**Comment by GoogleFrog** [comment]
what?

**Comment by Licho1** [comment]
Please reopen the PR @badosu it looks useful if engine really sends it.
We just don't have much time to review and test some changes. 
It will get looked into.

**Comment by badosu** [comment]
@Licho1 Scancodes have been supported for a while already, the change here adds handling for engine passed actions on 13xx+. Should be retrocompatible with older versions. The advantage of using engine passed actions is fixing keychain bindings for lua actions (e.g. `bind m,m say hi` says hi on double tapping m) and avoiding reconstructing keychains from provided keycodes (a very finicky and hacky method due to unplanned lua action implementation by original authors)

**Comment by badosu** [comment]
There should be a performance improvement but that's not significant at this runtime section

**Comment by badosu** [comment]
If your deployed engine version is 9xx+ scancodes should work, I removed the retrocompatibility for older versions so keep this in mind before merging.

**Comment by badosu** [comment]
A minor consideration engine passed actions allow is handling action chain halt with whitelists or blacklists by widgets receiving actions on keypress/keyrelease/actionreceiver.

**Review by Licho1 — APPROVED** [review]

**Pull request merged**
