### PR TITLE
Missing CUS shadows workaround

### PR DESCRIPTION
**Pull request by lhog**
https://github.com/ZeroK-RTS/Zero-K/issues/3734

In the future we should try to find someone else who doesn't see custom shadows in order to confirm the current theory of a buggy old NVidia driver.

### CODE REVIEW

**Comment by sprunk** [comment]
thanks!

**Comment by Zlodeiko** [comment]
> #3734
> 
> In the future we should try to find someone else who doesn't see custom shadows in order to confirm the current theory of a buggy old NVidia driver.

Well, I have exactly that problem like in #3734, which I can’t cope with for several months now. I don’t really remember if the shadows worked before, but now they don’t work (the shadows are visible only from the relief, some effects and nanoframes). 
I don’t have any buggy old nvidia drivers because I have radeon rx570 with latest drivers.
I tried some common solutions - reinstalled the game, reinstalled the video card drivers - with no results.
I read threads on this issue here - understood almost nothing. What are these .lua files and what to do with them? Can anyone explain in detail to a simple lobster how to make these damned shadows work?

**Comment by lhog** [comment]
I can send you some instructions how to work it around. In the same time I really want to understand why it might be happening and fix it properly. The fact that it doesn't work only for a few people suggests  me that something tiny is missing.  Are you tech savvy by a chance in a way that you can run custom widgets and upload the text or pictures they produce? If so contact ivand (another nichlkname of mine) on Discord.

**Comment by Zlodeiko** [comment]
Figured out a little. Added that "bug3734wa = 1" entry in springsettings.cfg and shadows appeared. 
But I also noticed another problem that may be related to #3734. I can see bumpmapping water only by turning it off in "menu - settings - graphics - map detail" and turning it back on. But after a restart, it does not appear again.

**Comment by lhog** [comment]
Yes, you could add a workaround that turns off custom shadow mapping, but it is what it says a "workaround". The proper solution is to find the cause and fix it. This issue is not reproducible on my GPU/drivers as well as for most of the players,  so I need someone with the issue and ability to put some extra files in the right places, run them and upload me results.

Are you qualified to do the above and willing to help?

**Comment by Zlodeiko** [comment]
Sounds like something not very complicated) I will try to. I'll write to Discord when I'm ready.

**Comment by lhog** [comment]
Thanks. Note, during the weekdays I'm only available for something more sophisticated than a quick chat in the evening after 6-7 pm (UTC+3)

**Comment by lhog** [comment]
I managed to identify the issue. At least for AMD. The issue was caused by drivers to not accept fragment shader of shadow map program. Normally this shouldn't be happening, but compatibility profile of OpenGL in spring and/or some FFP legacy setting in the engine cause the described behavior. Perhaps this combination is described somewhere, but it's like looking for a needle in a haystack.

In the end I worked around that issue the same way it's done by the engine. BAR has patched version of api_cus and material files. I should be able to make a PR for ZK once I have a spare minute.

**Pull request merged**
