### PR TITLE
Improve startup commander chassis descriptions

### PR DESCRIPTION
**Pull request by Legomenon-gh**
Attempt to reflect 1.8.3.2 changes to commander differentiation and
remove reference to dual wielding since all commanders can do that now.

Those strings are kind of hard to keep informative and concise, so feel free to reword them some more. (I'll update https://zero-k.info/mediawiki/index.php?title=Commander too)

### CODE REVIEW

**Comment by GoogleFrog** [comment]
Dual wielding refers to the ability to have two normal weapons. Recon and Engineer were always able to equip a normal weapon and a special weapon.

**Comment by Legomenon-gh** [comment]
Ha, I've updated the descriptions to read `can equip two normal weapons` which should be a bit clearer (though still not perfect since it's not very clear how the other chassis behaves).

Not sure how much detail should be given about the bonuses scaling but that probably belongs in the commander upgrade window rather than here (for Strike I mention levels explicitly since that bonus only kicks in at level 3)

**Comment by GoogleFrog** [comment]
Normal is not particularly clear. Maybe 'basic'?

**Comment by Legomenon-gh** [comment]
Yeah I reverted to "can dual wield", that's terser and clear enough in hindsight (and bringing up "basic weapons" in this screen is just more confusing than anything else)

**Pull request merged**
